apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret-argocd
  namespace: app
spec:
  encryptedData:
    application: AQBbmrr3T06+NG6sy/1nREK53ToOASB0brAiBPPqs/nbUI7EYclgFyo4YsJUvz9J09ry05DCYWns16/zjvVmgTxc8AY2dDQmAylTHPA9R/CQywj98s7WFspbmu9BddwvRdOBtpgVHmWi75N4jAJmxASWxAAqCa9sZGAE5x0teZ/yfhfMhJWdbmtE6KeXsZ03APgVMD0J38/j82rbbjJ2OVlUQYmzq+KBAAoCdaUAFChydwVqGNZBRzR5gHk1QRXpttV0VITe4Qt+kjrZjS1g2Mv7XgtkmhhLAqXcc7xC8LIc/rgrCdQya0YI5CSCoGbcmUrc7/sl97PGHFekgK1XzSMbYL4koeQ2W0wkPagorNlhxccQeuCMgQK4
    argocd: AQB+ODJBLRCmKw/JkU9Agdvc8ij/0DmIESVlxNKtX01sMby7KiZiqrx/Hojr1ZPUaz8avl9M7Y3lIPqtStb9SW387SzCMF89PEcC/Xl/Q3fBO23a7E2oKN7/aUgBgsi9h9XOF0JrUIckVlTsMrr6l/PguiiMWPle19D64HPaWtRy1N0YgI7uvLsaTRbnKq6c4YeZ9uXkrIF0yYkdATelbJSR87qUwXHYTZQ4ufzIqxOQgs3UkRdcEbLXsw1HRdCmYCt8CYif+SzPlJVuYORP29Nm1U/bwE/d2hMVbL+SF7jB7GdPy2sKnCT42TRd9G+CYY21KM5SMwPnD1kOx8ZTbRfVU72bLUxEVvBCXW06+dbWmzwZl+04
    secret: AQA6iqKb5+NTa8WHm8/cgtEOk85ARuTY6PJOJjTqMYJSnHu2Wqd+jwNJoRFePXsJ//6vqOxFGe6g8UGCsKeDjkzqC7Jarh3rw2y1WX3rfFAkhOAru+qTs7Vm1vc5bf+hP8sFiesJt1oD68Xo+ctRHB1t36GFnTGhNez+43bS9VDVS4RzRivFTOaN4z9tGUa3sAEn4uvBXKSC5XDQHNUo3MY/MZbgB+MYT0HgFEgH1qaP8yOntpK4tdi3WZEerp8NOVDL3WPmWPN27CKQprwcKE/rkhPuFCifFeJCbujaqquPvmaO1himeAgM0Mvwfz7URH3ScXvhXTMbT01p+FKOdQGVEk8iajl68Toeb6yKfKkX99KiGM9cJQGRw5bS5eeXfK0=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret-argocd
      namespace: app

