apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: myargocdsecret
  namespace: app
spec:
  encryptedData:
    foo: AQCkaORfX2rSVJWIPFNUJW/gIp1CvrYE9qy1bQAsMaveAb4+6E53AH9JQM2uuuazXjxTk7LCBaGlUi2RxF9R+jfQxxp4OOJ8eccjmg3OHdYQdK7R+omzRUROlXQLchPmJKTgnmMQqUtReOFkslsfYsRUS82HnJkM54xdW9WW2sff7rCami4v/9+xBmIcjfa1oL1Rgags3aU40BiYUn9mrgxM1m4A7LtaZ56E8NEvrr9OLlyzG1Roar5S6tuFtOGniYWB4wbH3Wmjrr0pr53jmyWKfuwAWMC8FqDX7C/JviLRcEAzYi+3TSRFaYAdGgeWqnk6ZCP8bPKJvn8WgYu03xNgTWkZ64bo5IYjWilCI0rm+C5v5Q==
  template:
    metadata:
      creationTimestamp: null
      name: myargocdsecret
      namespace: app

