apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-sealedsecret
  namespace: argocd
spec:
  encryptedData:
    application: AQCIZfkzWM2yjG4BRzeiiAxJhrlb8BS4AbadROmSuXH2oBfvAbKU8jITIGaeiF/ZWDLhWs00LnRYqg9tY7uHGdL39XcgWe2MZG3ACoIuA+DFzyh8Lz6R1xjo2eJfXugzPzi2AhLug6joBpIkdqkXdcZASstppiyJ9kevqO5n14hpQ43BjrxdKA/ekAiP4j0Xw5Srb9VcvrvWGRcJ3QmjGB1Is6wvaiqQnZFcEFXUcl5PP6el7RLFo24IF1UTqaeYRZV/8I6Cc8R+X3S5/am1/8kY4/UULJrO1Bftv+Ne5RDZaExjc2CwMPHlAWJZOSHxSVae2x3rmNjyPvoLh6KU1EmKg2xF+i5Y2e53aL1es3/8dT5kqLLaxOLT
    argocd: AQBxCWN+0BKb1e1pTJAZzNxIeQUd8lAbtCBwZ39b0UG4NYyOxyUwYqRdi57qIcsjf0xUZf8hs55B4ehMx0pSNFk3jB7Ez4bmcQbi6KQECPeqICDM53mSnH+E6UNgnbyccL6qP6g+vVs7ukcIU6W4kzYe+Z4J32i3XErq7bjDZgCUu+7AoARNwXEVycaUIdJirvKGfPjBq143sknIjY3ImcuWEgnmR/w08VNHMQdTuDQwKjF02WDIPJ0pBmTcZSWAYkv7BXA8TEsey2VfRM6x55tkRFobM7T2BqvA4bJnk+jjBTa6FuEvATAkQvM7ZvYyR7C96R4q7o7khF0yK+hhf8Ye5tWB3EU3jj4IIsFYOZGIs13UPHLu
    secret: AQBJFFXBbU364m/aIxSUUp983LWGzoWwQbOKDHojJd8p27Tb+7vfGJWDhUDppCljQVDllrlc4cxr1QarpBTf5PfzGE4/72xTjytZlXxdhQUkXqu3biw30SbwNTjsRgism9Qct2kAOFkELQYg8hdCFALf894iQjCrYXdAoNug1fVUpzy+ZEEFBqFltPLg30qecLnzL3nxTvUNK/uLGsztYehf6GBgMaimOfXgBHSmN3P1n8Q0ZMEz63PeVlLq3SDnLZCrH49ZlIO9y7c/oq4PXNlFxSi5P8ByZJ22FI+q53XbIDr5VNXKsCr5nk7QtW7cCRr0wwwpj3mIqJ0XuNZCEpc/Xi+HlnDm92l/Krx9KSajOaJ1nNm0f/2vX37orVX9NZM=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-sealedsecret
      namespace: argocd

