apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-sealedsecret
  namespace: app-sealedsecrets
spec:
  encryptedData:
    application: AQAoumsHR6n3G4OOXTlRpJqen3LwJCFJmtjVH48bWHJDedJ8pzURsSvBh/xojR90VdWG8ylMZC+KZcpB8j8UkhnHOHnyWi1n5P0sLD9YcomVpdYJjcbbsllspL+LT1Ifj9qI/6i8ou2noFGVQaQDaJUujSJm5ehFD+dkIOwIgqqiJD6q5l2FCEEUN8wrGDiBCi39xWopOK9OQhLXdTDOALeX8e0Jti8RYsk10Aou/XBdsUlJJcS8pnlJsHeKwLOY5Muz+GLL4AVgUlzY/waiJVBlvLAdUBIV5mVRLTMB62c5nEHJxRLtCHoy43P4mXU79fYvgxLYB9tYq5XwDp+8Kw0AOkuH4GLdXiQWj4hSDih/jshd4qjO6fT/
    argocd: AQA/SvhATmhoawSt7CstwkBilBGhMZ26/AaQ0pJSPsr98YhuLBeCHW60BIOFcGPf/fQ3k0ewBtNlXh8ahXMLPZvr5A3UK/W7u8rhTZw8LS9Yv6y6QidAkTRzeP1YbT/Z4romi7hIgIQeAMTdVXpfMj/DqVDbsA+EWD1dcfrhblmA8xjXwhwquqaYWIyMvx+dtNQ6RPr76ae+Ioxwbq6U2KkMx/6huVN3rbwLDNGudsuirhKQ+JELEwaOBIJGjMeGu9HimWNxgT81Cr0HLHkzWWJNI4ioHwZrJHh6CoolsZUjY+Soy85JIKXmaiAV4CKw7FQANleZfdtm6LOzhJifKimUo8cFnlNHBQr+k9GUDZn4chQcH2hE
    secret: AQCMox0k5aCLaJ4w2qU0Lqp/iVlmDLPZOFYae7wZJt9Prq+lFLt+DoGlBKKKNYz/waYOoQzD5086YlfuROcCWbWy5H08bDX9bRv1uWyzvvpWEzmaVWMit9nt/LuU0ZqX22XFqXFFpT0nRxkxQWRAizl46iv4MQOUAm54YBUvnUHOVrcALm6xo8c0S6IUP6COmA4krWEe5D0Httzw2Hgz1/MLJxD0kuNPq2ZSCXvR8c5QPsIBTZmJZkJDfQoaGhTQi6lZe53B+QheVXIINZYc20PO93+rvzdh0fyOI9rOnu04XvxZowW7pDr0lLEA6ndSVBvoZSn9wN+Jh6nrNZLRzJop0Nt5PF0pc258xe12j/sHfllOfhbZp6aGA1R7Xumsg/8=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-sealedsecret
      namespace: app-sealedsecrets

