apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: app
spec:
  encryptedData:
    foo: AQBxVOJ3vg0jbyYMgASa/xctjnA7e5CpEdup6IAYPXMnm+cxDnEYhkfayDZrqCkheZJKEpsZE5/LPlRI/gL11wjXfYodEXea3YoB7VUwadeVr8zTJU/bXsw/axKTtfQSYIC9HDRAUaXUYM8+ydNOMpDOTYFinI4gHQ7o7xcuOcHjbb3I4Fr+/GLd9edkmO2yarEbbbMjeWxVbZHbHnnrDMIMrkv5o+iqOsMcQDpccQ1CrnlVDFOJtYAeP1Nbd6gCCYKR8EFrVccKhzM+b3qv9bOPdXqyMOmDeUT9DJPstfk7y0rhsecQC25iFox0wBTFo7XJ1PGUJJblYAdaidlBvkzsUhsxcfMgfue5rHhVIz3lt+q1fA==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: app

