apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: app
spec:
  encryptedData:
    foo: AQA88FeoZHMedw1RGCwiu4SU1pOwsl3OuA3SxroOTS53vpNwS2XgXYVTftmqRdUWokWGKrTCKeaNCLinJ2cURhjx+jatrQjVqq0mW9wJhgkr3VtzWNgElkw4uXbV0mycaXZ8wzjwxkZLzyJocytlsgIeJskEovkEfiM/MZQp5pFfEmGcrZWO7I76eBiIpCEUaTZkYu5qDD7iP50XEd8B0Q2LZFETYD523xm3Ped6IWNOhmVFnGUm2WvBxW2FtyMQJYcAJrGy+7BsMFNuJ5Q7CKGqjgR6ZA/tHDfVxiYW8JNRmk6aXjwgcAFHCCuvwf3hUPvio0pi4lXjv3mhUB7004NqRiILLGEKiCxzpV0rGUekM4ejpg==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: app

